
SELECT *
  FROM XXTG.XXTG_EXPENSE_CONTRACTS
 WHERE CONTRACT_ID = 20146
 
/*Список Rent contracts для добавления признака Единоличных контрактов */
UPDATE XXTG.XXTG_EXPENSE_CONTRACTS
   SET IND_ACT_FLAG = 'Y'
 WHERE CONTRACT_ID = 19039
 
 = "UPDATE XXTG.XXTG_EXPENSE_CONTRACTS SET IND_ACT_FLAG = 'Y' WHERE CONTRACT_ID = " & A2